### ISSUE TITLE
Support custom bundler version 

### ISSUE THREAD

**Issue by jgao54** [p0deje/rules_ruby#2]
Is there a way to support installing a specific version of bundler when setting up the ruby toolchain? Currently this is not configurable, afaik; instead the default version of bundler corresponding to the ruby version is used.

**Comment by p0deje** [comment]
Is this a problem? Usually, if your `Gemfile.lock` needs a different Bundler version, it would automatically install it on the first  invocation.

**Comment by jgao54** [comment]
ah, it looks like this is the case with bundler 2.3+, we are currently on 2.2 so it does not.

**Comment by p0deje** [comment]
What Ruby version do you use? Ruby 3.0 already ships with Bundler 2.3. Can you share relevant `WORKSPACE`/`Gemfile.lock` parts?

**Comment by p0deje** [comment]
I suggest we close this for now since Ruby 2.7 is EOL. Let's revisit if it's needed for migration.
