### ISSUE TITLE
rubocop failure on Windows due to line endings

### ISSUE THREAD

**Issue by alexeagle** [p0deje/rules_ruby#27]
We had a red build on the Bazel Central Registry:
https://buildkite.com/bazel/bcr-presubmit/builds/2569#018c02af-083a-4eff-88ba-7f8ccbae9ff5

I'll disable Windows for now to land that PR, but I suspect this is trivial to fix for the next release?

**Comment by p0deje** [comment]
I wonder why ruleset CI was passing, but anyway the fix is pushed now

**Comment by alexeagle** [comment]
Now the CI on this repo is red on Windows. Must be something trickier going on.

**Comment by p0deje** [comment]
1. In our CI we have CRLF line endings on Windows (expected).
2. in Bazel CI we have LF line endings on Windows (failure).

It might be related to how Bazel CI fetches sources. On GHA we use Git checkout and I guess it's responsible for setting proper line endings. @alexeagle Do you know how Bazel CI does it?

**Comment by p0deje** [comment]
https://buildkite.com/bazel/bcr-presubmit/builds/2569#018c02af-083a-4eff-88ba-7f8ccbae9ff5/60-63

I suppose the line endings are not fixed when uncompressing the archive.
