### ISSUE TITLE
non-hermetic bundle install

### ISSUE THREAD

**Issue by jgao54** [p0deje/rules_ruby#5]
bundle install [passes in PATH variable](https://github.com/p0deje/rules_ruby/blob/4ba2cd7e5be924bafd7c6c9ed2868fa7a73ca9ee/ruby/private/bundle.bzl#L40), which can head to non-hermetic builds. 

In our case, we had `$GEM_HOME/bin:$BUNDLE_PATH/gems/bin:` in our PATH variable that resulted in gems getting downloaded in a different directory.

May be better to remove PATH altogether.

**Comment by p0deje** [comment]
I don't remember why I implemented it like that, but I think that w/o PATH and certain common dependencies, it failed to compile native extensions. It would be great to solve it, but I'm not sure how exactly. The implementation implies that gems will be installed into the Ruby toolchain, so PATH should not have affected that.

I also currently work on a completely new bundle implementation that only fetches gems in a repository rule, but actually installs them in a separate regular rule. This should in theory make it work in the RBE environment (e.g. gems are fetched on a macOS machine where WORKSPACE is evaluated, while installation happens in a remote Linux machine where BUILD is executed). When I finally make it work properly, this issue might be solved as well.

**Comment by jgao54** [comment]
Dug into this a bit more, and discovered that my original diagnosis was not quite right. PATH environment was not the cause, but instead it was BUNDLE_PATH, which is loaded in the following order:
1) `BUNDLE_PATH` set in `$BUNDLE_APP_CONFIG/config`
2) `BUNDLE_PATH` set in `<project_dir>/.bundle/config`
3) `BUNDLE_PATH` env var directly
4) `BUNDLE_PATH` set in `~/.bundle/config` 

`bundle install --path [directory]` is the simplest fix i think. Although, according to [official doc](https://bundler.io/v2.4/man/bundle-install.1.html), it is being deprecated in favor of the `path` in config setting mentioned above.

So propose this instead: set `BUNDLE_IGNORE_CONFIG=1` to avoid parsing any bundle config files, and set the `BUNDLE_PATH` env var to the desired location in bazel's output directory (the [remaining bundle configs](https://bundler.io/v1.12/man/bundle-config.1.html#LIST-OF-AVAILABLE-KEYS) can still be supported by introducing an `env` var to `rb_bundle`).

**Comment by p0deje** [comment]
Rules currently don't use `BUNDLE_PATH` at all and instead install gems into the Ruby toolchain itself. We might switch and use the desired path, but can we try first by simply adding `BUNDLE_IGNORE_CONFIG=1`?

**Comment by p0deje** [comment]
Would

**Comment by jgao54** [comment]
Thanks; tested it out. This definitely fixes the issue for BUNDLE_PATH specified in config files (1, 2, 4 above). However if BUNDLE_PATH or GEM_HOME environment variables are set (3, 5 above), it will still direct the gem to be downloaded to the location specified by the env var.

You can also repro it locally by:
1.  `export BUNDLE_PATH=<some_path>`
2. `BUNDLE_IGNORE_CONFIG=1 bundle config get path`

**Comment by jgao54** [comment]
Fixed with https://github.com/p0deje/rules_ruby/commit/0c2c290bdc4468186de3a786976c1e2b3dc8c2bc
